#!/bin/bash

git status -s > /tmp/gstat

nmod=`grep -e '^.M ' /tmp/gstat | wc -l`
nadd=`grep -e '^?? ' /tmp/gstat | wc -l`
ndel=`grep -e '^.D ' /tmp/gstat | wc -l`

if [[ $nmod -ne 0 || $nadd -ne 0 || $ndel -ne 0 ]]
then

    echo "Modified:"
    grep -e '^.M ' /tmp/gstat
    
    echo "Added:"
    grep -e '^?? ' /tmp/gstat
    
    echo "Deleted:"
    grep -e '^.D ' /tmp/gstat

    echo "Are you sure you want to continue (yes/no)?"
    read a
    
    if [[ $a != "yes" ]]
    then
        echo "Aborted."
        exit 1
    fi
fi

HASH=`git rev-parse --verify --short HEAD`
VERSION="`cat current_version.txt`"
HVERSION="$VERSION ($HASH)"

echo "Current version: $HVERSION "

git tag -a $VERSION -m "Version $HVERSION"


# Update versions in source

for f in *py
do
    grep -q -e '^VERSION=.*Adjusted by make_release' "$f"
    
    if [[ $? -ne 0 ]]
    then
        continue
    fi
    
    sed -e "s|^VERSION=.*Adjusted by make_release|VERSION=\"$VERSION\" # Adjusted by make_release|" < "$f" > "$f.py.tmp" && mv "$f.py.tmp" "$f"  

done


